language: node_js
node_js:
  - "8"
before_install:
  - npm install
install:
  - npm run build
script:
  - npm run lint
  - npm run test
  - npm run coveralls
deploy:
  provider: npm
  email: "bromne@gmail.com"
  api_key: $NPM_TOKEN
  on:
    tags: true
